# Generated by Django 4.1 on 2022-09-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('BookingId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('BookingType', models.IntegerField()),
                ('BookingDate', models.DateField()),
                ('bookingComment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cookings',
            fields=[
                ('CookingId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('BookingType', models.IntegerField()),
                ('BookingDate', models.DateField()),
                ('bookingComment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lookings',
            fields=[
                ('LookingId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('BookingType', models.IntegerField()),
                ('BookingDate', models.DateField()),
                ('bookingComment', models.CharField(max_length=255)),
            ],
        ),
    ]
