# Generated by Django 4.1 on 2022-09-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newnew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('ActionId', models.AutoField(primary_key=True, serialize=False)),
                ('ActionType', models.IntegerField()),
                ('ActionDateDate', models.DateField()),
                ('bookingComment', models.CharField(max_length=255)),
            ],
        ),
    ]
